### ISSUE TITLE
MySQL 1146 error while setting up and running the devserver.sh

### ISSUE THREAD

**Issue by harshitcodes** [Spoken-tutorial/spoken-website#74]
Got the error after creating the config.py by running the setup.py and then when I run the command to run the devserver.sh, it give me this:
django.db.utils.ProgrammingError: (1146, "Table 'DB.creation_fosscategory' doesn't exist")

**Comment by theskumar** [comment]
Hi @harshitcodes, please try the pull-request i have here: https://github.com/Spoken-tutorial/spoken-website/pull/75 and you can close this pr as applicable. Thanks.
